USE travel_money_cards;

INSERT INTO currency_codes(currency_code,currency_name)
VALUES
('AUD','Australian Dollar'),  
('BRL','Brazilian Reals'),  
('BGN','Bulgarian Levs'),  
('CAD','Canadian Dollar'),  
('CNY','Chinese Yuan Renminbi'),  
('HRK','Croatian Kunas'),  
('CZK','Czech Koruna'),  
('DKK','Danish Kroner'),  
('EUR','Euros'),  
('HKD','Hong Kong Dollar'),  
('HUF','Hungarian Florins'),  
('INR','Indian Rupee'),  
('IDR','Indonesian Rupiah'),  
('ILS','Israeli Shekel'),  
('JPY','Japanese Yen'),  
('KRW','Korean Won'),  
('MYR','Malaysian Ringgits'),  
('MXN','Mexican Pesos'),  
('NZD','New Zealand Dollar'),  
('NOK','Norwegian Kroner'),  
('PHP','Philippine Pesos'),  
('PLN','Polish Zloty'),  
('RON','Romanian Leus'),  
('RUB','Russian Rubles'),  
('SGD','Singapore Dollar'),  
('ZAR','South African Rand'),  
('SEK','Swedish Krona'),  
('CHF','Swiss Francs'),  
('THB','Thai Baht'),  
('TRY','Turkish Lira'),  
('GBP','Great Britain Pounds'),  
('USD','US Dollar');